### ISSUE TITLE
Binding size issue in latest Chrome Canary

### ISSUE THREAD

**Issue by scratcher28** [vladmandic/human#324] opened 2022-12-29 13:46 UTC
**Issue Description**

Binding size (104) is smaller than the minimum binding size (112).
 - While validating entries[2] as a Buffer.
Expected entry layout: { binding: 2, visibility: ShaderStage::Compute, buffer: { type: BufferBindingType::Uniform, hasDynamicOffset: 0, minBindingSize: 112 } }
 - While validating [BindGroupDescriptor] against [BindGroupLayout]
 - While calling [Device].CreateBindGroup([BindGroupDescriptor]).

When running main demo and image as an input (video not tested).
Also tested in Chrome 108.0.5359.125, no issues, but it runs deadly slow on RTX3080 10GB.

**Steps to Reproduce**
just run a demo: https://vladmandic.github.io/human/demo/index.html and any image as an input.

**Expected Behavior**

**Environment**
Chrome Canary **111.0.5506.0**, Windows 10 64-bit.

- Human library version?
3.0.1 (webgl backend), but it seems all versions affected.

**Diagnostics**
![screenshot](https://user-images.githubusercontent.com/778716/209961953-9bbc5f3c-f1b6-4228-bdee-73a6c52e7b9e.png)

**Comment by vladmandic** [comment] 2022-12-29 15:50
Interesting.

I'll take a look next week, I'm away right now.

**Comment by vladmandic** [comment] 2023-01-06 18:22
i just tested on multiple platforms and i cannot reproduce:
- edge 108.0.1462.54
- edge 111.0.1604.0 canary
- chrome 111.0.5522.0 canary

any other info you can provide?

**Comment by scratcher28** [comment] 2023-01-07 09:53
I had `enable-unsafe-webgpu` enabled for some reason I can't remember now, after disabling it I was still getting the same errors. The issue resolved as soon as I updated to humanjs v3.0.2. Updated Chrome Canary to 111.0.5524.0, everything is fine now.

**Comment by vladmandic** [comment] 2023-01-07 10:28
human by default tries to pick best available backend and it fully supports webgpu, but webgpu is still experimental in chrome so human cannot use it by default. by setting that flag, you enable webgpu and human is more than happy to use it :)

the issue you've originally mentioned is limited to webgl, so as soon as you started using webgpu i don't expect to see it.

seems there was an interim issue in chrome and webgl minimum uniform sizes, but its resolved.  
i'll close the issue, but feel free to post on this thread with any questions/updates.

**Closed by vladmandic** 2023-01-07 10:28 UTC
Labels: question
