### ISSUE TITLE
Apple Mac OS M1 support

### ISSUE THREAD

**Issue by kzpromo** [vladmandic/human#262] opened 2022-03-31 18:41 UTC
**Issue Description**
Uncaught Error: The Node.js native addon module (tfjs_binding.node) can not be found at path: /Users/kzpromo/Documents/Browser/NewClearEx/node_modules/@tensorflow/tfjs-node/lib/napi-v8/tfjs_binding.node. 
Please run command 'npm rebuild @tensorflow/tfjs-node --build-addon-from-source' to rebuild the native addon module. 
If you have problem with building the addon module, please check https://github.com/tensorflow/tfjs/blob/master/tfjs-node/WINDOWS_TROUBLESHOOTING.md or file an issue.
**Environment**
mac m1

i got errors, but npm rebuild @tensorflow/tfjs-node --build-addon-from-source dont help solve my problem

help fix this error

**Comment by vladmandic** [comment] 2022-03-31 20:21
This is not related to `Human` library, but to underlying support of TensorFlow for Apple's M1  
See <https://github.com/tensorflow/tfjs/issues?q=M1> for list of all issues related to it  

Anyhow, TFJS support for M1 was added about 2 months ago via <https://github.com/tensorflow/tfjs/pull/5899>, so should be in latest version of `@tensorflow/tfjs-node`. If its not working, file an issue in tfjs repository  

Btw, issue template exists for a reason - next time please fill the template as you haven't even provided basic information such as which version of tfjs you're trying to install  

Closing as root cause is TFJS support for M1.

**Closed by vladmandic** 2022-03-31 20:21 UTC
