### ISSUE TITLE
mesh not supported in nodejs

### ISSUE THREAD

**Issue by meeki007** [vladmandic/human#80] opened 2021-03-01 01:07 UTC
**Issue Description**
When running the demo/node.js the face mesh does not work
Thought this was just a demo issue but when I run it on my own provided image(picture of a face/person) I get every thing but the mesh as well.

**Steps to Reproduce**
run the demo/node.js

**Expected Behavior**
mesh: "some value here"

**Environment
- NodeJS and version
NodeJS 12
- OS and Hardware platform
Ubuntu 20.04 Linux on x64

**Comment by meeki007** [comment] 2021-03-01 01:10
oh also:
using "Human:0.20.9"
and "TFJS Version:"2.8.6""

Updating now and will try again

**Comment by vladmandic** [comment] 2021-03-01 01:11
That's expected behavior, will update here in more details tomorrow.

**Comment by meeki007** [comment] 2021-03-01 03:52
Understood. I say wait for blaze face!!!
even if I had the skill to linkup facemesh to faceboxes It would be work in the wrong direction as blazeface sounds like the direction to go.

I totally understand not wanting to do a bunch of code for a antiquated solution that may be fixed later.

saw links and read about tfjs-node and the balzeface issue and while working on my node-red node I put in the code for it now in hopes of it being fixed in a few months.
```
<select id="node-input-FaceDetector" style="width: 70%">
            <option value="faceboxes">faceboxes</option>
            <!-- <option value="blazeface-front">blazeface-front</option> -->
            <!-- <option value="blazeface-back">blazeface-back</option> -->
            <option value="disabled">disabled</option>
        </select>
```
all I have todo is comment it and its supported !!!

Thanks for all you do.

**Comment by vladmandic** [comment] 2021-03-07 15:11
i'm closing this issue since it's been tracked via <https://github.com/vladmandic/human/issues/1>

**Closed by vladmandic** 2021-03-07 15:11 UTC
Labels: enhancement, fix required upstream

**Comment by vladmandic** [comment] 2021-03-09 23:40
`blazeface` and `handpose` have been enabled in tfjs-node with `Human` version 1.0.2
only missing feature in `tfjs-node` is matrix rotation which means mesh detection will be poor if face is at the high angle, otherwise it's identical to browser.

as there is no need for it anymore i've removed `faceboxes` model.
