### ISSUE TITLE
if image.process throws node app dies

### ISSUE THREAD

**Issue by hillar** [vladmandic/human#207] opened 2021-11-09 13:17 UTC
https://github.com/vladmandic/human/blob/b16bb2e8ac6886dede12e9155bbc9d8f811bd5f5/src/human.ts#L420

```
/app/sk/my-app/node_modules/@vladmandic/human/dist/human.node.js:1016
      throw new Error(`input tensor shape must be [1, height, width, 3] and instead was ${input["shape"]}`);
            ^

Error: input tensor shape must be [1, height, width, 3] and instead was 1,100,100,4
    at process2 (/app/sk/my-app/node_modules/@vladmandic/human/dist/human.node.js:1016:13)
    at /app/sk/my-app/node_modules/@vladmandic/human/dist/human.node.js:13064:25

Node.js v17.0.1
```

temporally fixed with `try .. catch .. resolve({error})`

**Comment by vladmandic** [comment] 2021-11-09 13:43
yes, that is by design - if input is invalid, what should be the behavior, just ignore it?

**Comment by hillar** [comment] 2021-11-09 14:04
same as with failed tensor https://github.com/vladmandic/human/blob/b16bb2e8ac6886dede12e9155bbc9d8f811bd5f5/src/human.ts#L425

```
let img
try {
  img = await image.process(input, this.config) as { canvas: HTMLCanvasElement | OffscreenCanvas, tensor: Tensor };
} catch (error) {
  if (this.config.debug) log('could not process input image');
  resolve({ error: 'could not process input image' });
  return;
}
```

**Comment by vladmandic** [comment] 2021-11-09 15:14
i disagree, using any possible input that human is going to try to process is not the same as using tensor which will be used as-is without any processing.

**Comment by vladmandic** [comment] 2021-11-09 19:41
closing as works as designed

**Closed by vladmandic** 2021-11-09 19:41 UTC
Labels: wontfix

**Comment by hillar** [comment] 2021-11-09 21:43
> i disagree, using any possible input that human is going to try to pre-process is not the same as using tensor which will be used as-is without any pre-processing.

agreed, not the same

however,  please reconsider

`human.detect` https://github.com/vladmandic/human/blob/b16bb2e8ac6886dede12e9155bbc9d8f811bd5f5/src/human.ts#L392 throws on perfectly ok image files and as it is behind `await`, there is no way to trycatch it in node app ;(

```
const buffer = fs.readFileSync(inFile);
const tensor = human.tf.tidy(() => {
  const decode = human.tf.node.decodeImage(buffer, 3);
  const expand = human.tf.expandDims(decode, 0);
  const cast = human.tf.cast(expand, 'float32');
  return cast;
});
return tensor?.shape ? await human.detect(tensor) : undefined
```

**Comment by vladmandic** [comment] 2021-11-09 22:30
> throws on perfectly ok image files

can you explain this?  

in the first post your input tensor was RGBA and TFJS requires RGB - thus the error  
and code you just quoted explicitly converts to RGB, so that's not the code that resulted in RGBA tensor in the first place  

for this specific case, i could implement enhancement to strip alpha channel within the library so allowing shape `[1, width, height, 3 || 4]`, but that is not the ask here  

btw, i tried handling this without `throw` and then i get some users asking why do they don't get results when using human and i have to spend time troubleshooting.

**Comment by hillar** [comment] 2021-11-09 23:08
> in the first post your input tensor was RGBA and TFJS requires RGB - thus the error and code you just quoted explicitly converts to RGB, so that's not the code that resulted in RGBA tensor in the first place

mhmh, first case was example from wiki Usage#example-for-nodejs, second one from demo nodejs/process-folder

so for me it was _perfectly ok image_


> btw, i tried handling incorrect tensors without `throw` and then i get some users asking why do they don't get results when using human and i have to spend time troubleshooting.

mhmh, in browser it is better to have *throw* as it points directly to _reason_, in node oposite, bad input killing your app is BAD

**Comment by vladmandic** [comment] 2021-11-09 23:15
> mhmh, in browser it is better to have throw as it points directly to reason, in node oposite, bad input killing your app is BAD

I'd agree with that. But I have more browser users than node, so...
Lets try to improve whatever can be improved  

I'll add automatic strip alpha and batch dimension expansion, so valid input tensors will be:
`[1, height, width, 3 || 4] || [height, width, 3 || 4]`  

> first case was example from wiki Usage#example-for-nodejs,

docs are updated.

btw, I appreciate detailed reports - makes it very easy to track things down

**Comment by hillar** [comment] 2021-11-09 23:22
> I'd agree with that. But I have more browser users than node, so...

somethin similar `..typeof Path2D !== 'undefined' ..`

like

```
let img
try {
  img = await image.process(input, this.config) as { canvas: HTMLCanvasElement | OffscreenCanvas, tensor: Tensor };
} catch (error) {
  if (typeof window === 'undefined') {
    if (this.config.debug) log('could not process input image');
    resolve({ error: 'could not process input image' });
    return;
  } else throw error;
}
```

**Comment by vladmandic** [comment] 2021-11-09 23:40
i've tried creating generic handler, but then you loose information where actual error happens since `throw` happens inside a handler. and adding `if...then` everywhere is well *ugly*.

but isnt that a philosophical question if library automatically handles different tensor shapes?

like i said, my goal is to handle whatever i can inside the library and only throw on real errors that cannot be avoided

**Comment by hillar** [comment] 2021-11-09 23:46
> but isnt that a philosophical question if library automatically handles different tensor shapes?

if it handles, then yes

**Comment by vladmandic** [comment] 2021-11-10 00:39
done, library now handles tensor shapes internally  
new code is in main branch  

    passed: tensor shape: [ 1, 1200, 1200, 4 ] dtype: float32
    passed: tensor shape: [ 1200, 1200, 4 ] dtype: float32
    passed: tensor shape: [ 1, 1200, 1200, 3 ] dtype: float32
    passed: tensor shape: [ 1200, 1200, 3 ] dtype: float32
    passed: tensor shape: [ 1, 1200, 1200, 4 ] dtype: int32

i'll update `nodejs` docs and demos tomorrow as they can be simplified by quite a bit now
