### ISSUE TITLE
Error loading WASM backend

### ISSUE THREAD

**Issue by simon-lanf** [vladmandic/human#26] opened 2020-11-09 21:02 UTC
Hello, let's continue here.

I have this error message when loading the demo on localhost.

![1604955466_grim](https://user-images.githubusercontent.com/58534677/98595841-8bc73000-22a4-11eb-8cc0-e82a073e5138.png)

The only thing I did was clone the repo, update demo/index.html to uncomment the 3 lines for wasm/webgpu and then npm run dev. Then I select WASM and then I start the camera if breaks hard.

![human](https://user-images.githubusercontent.com/58534677/98596122-fbd5b600-22a4-11eb-88f3-d8357f638e4f.png)

Have a nice day.

**Comment by vladmandic** [comment] 2020-11-09 22:15
this is a memory access out-of-bounds during wasm startup - really weird.  

i can reproduct if i switch to wasm backend before startup, but if i start run with webgl and then switch to wasm, no issues.  

i'll dig more.

**Comment by vladmandic** [comment] 2020-11-09 22:26
There seems to be a binary bug causing memory access error if Tensorflow WASM backend is deployed as ESM instead of old-school module and I use ESM exclusively in my library. 

As a workaround, enable SIMD in your browser - that enables parallel instructions (that is recommended for WASM anyhow as it allows WASM to use more modern CPU instruction set)

Chrome:
- Navigate to <chrome://flags>
- `WebAssembly SIMD support` set to Enabled

Edge:
- Navigate to <chrome://flags>
- `WebAssembly SIMD support` set to Enabled

Firefox:
- Navigate to <about:config>
- `javascript.options.wasm_simd` set to True

I'll keep this issue open and discuss it with TFJS devs.

**Comment by simon-lanf** [comment] 2020-11-09 23:31
Sadly, I cannot support SIMD because I am building on Android for Capacitor and I run my app in a locked down platform. There is no way for me to set the flags to enable it.

But my app currently works this way with TFJS' blazeface in WASM mode. Isn't there a way to mix both ESM and non ESM ? Otherwise I will try to extract your model for the back camera to use it standalone.

**Comment by vladmandic** [comment] 2020-11-09 23:36
i'm looking for a way to embed `tfjs-backend-wasm` without bad sideeffects.
currently i'm running into issues that `tfjs-backend-wasm` is simply not built the same way as the rest of `tfjs`, so embedding it directly is pretty messy.

give me a day.

**Comment by simon-lanf** [comment] 2020-11-10 01:18
Thank you for your awesome work !

**Comment by vladmandic** [comment] 2020-11-10 01:21
ok, here it is:
- new version of `human` with `tfjs-backend-wasm` bundled is published, do not load any scripts from `index.html` anymore
- both wasm with and without simd work

but...
- without simd, wasm has serious concurrency issues, so trick is to start with a single model enabled only  
  (e.g. only 'face detect') and once it is initialized, you can enable additional models one by one  
- with simd, no such issues

of course, simd is so much more faster than non-simd, so more complex models such as `hand` and `body` are barely usable without simd anyhow.  

i've added a wiki article: <https://github.com/vladmandic/human/wiki/Backends>

**Comment by djthegr8** [comment] 2020-11-10 04:31
@vladmandic WASM gives 3-4 fps at maximum (hand only, maxHands = 1, landmark = false) with SIMD, can this be improved

**Comment by simon-lanf** [comment] 2020-11-10 05:11
@vladmandic all my tests show me that with every Android device I tested, WASM is by far the fastest, even without SIMD. On my phone on your demo with few models I can get 10 fps on WASM and 3 fps with WebGL. Can you reproduce these results ? Maybe it's an error on ny part.

**Comment by vladmandic** [comment] 2020-11-10 11:49
@simon-lanf 

Depends on a hardware (on both mobile and desktop):
- WASM executes on CPU in a native compiled code  
  SIMD means that code can use newer extended CPU instructions  
  for parallel processing and thus it's much faster  
- WebGL executes on GPU using GL calls which are processed by browser  
  So a lot depends on browser's implementation of WebGL as well  
  E.g, Chome is about 2x faster than Firefox at the moment but uses far more memory  

And both WASM and WebGL have very specific weak points:
- WASM does not have hardware-accelerated image buffer handling  
  So simply preparing image for processing is expensive  
  That's why you get big gains when you reduce input resolution  
- WebGL needs to compile the GL code and transfer data to GPU  
  So there is an overhead before processing actually start  
  This is especially visible at startup (so-called "warmup")  

So if your CPU is faster than your GPU, WASM is faster. But if you have a good dedicated GPU chip (on desktop or mobile), WebGL will by faster.

Perf tests:
- On my mobile Samsung S20Ultra with all models enabled, WebGL executes with 6+FPS and WASM with barely 2FPS  
- On my notebook with Intel i7 and nVidia 1650Ti, WebGL executes with 20+ FPS, WASM with barely 4FPS and WASM with SIMD with ~8FPS  
  But if I reduce input resolution to 720p, WASM with SIMD jumps to 15FPS and continues to climb with even lower resolutions

**Comment by vladmandic** [comment] 2020-11-10 11:50
@djthegr8 I'll see what I can do, but biggest gains to WASM are by reducing resolution - it helps a lot!

**Comment by vladmandic** [comment] 2020-11-11 20:08
@djthegr8 @simon-lanf  

fyi, i've created an issue at `tfjs` to provide improved image data loading for `wasm` backend  
currently it's only implemented for `webgl` and difference is drastic: webgl: <1ms vs wasm: >20ms  
<https://github.com/tensorflow/tfjs/issues/4218>

also, regarding wasm (non-simd) memory issues, it is also being tracked at `tfjs` level  
<https://github.com/tensorflow/tfjs/issues/4208>

since all the original questions have been addressed, i'm closing this issue

**Closed** 2020-11-11 20:08 UTC
Labels: question
