### ISSUE TITLE
Facemesh "beating" with the latest human

### ISSUE THREAD

**Issue by ButzYung** [vladmandic/human#221] opened 2021-11-20 08:14 UTC
There is a strange problem regarding facemesh in the latest `human`. The detected facemesh keeps "beating" periodically, shriking in size at a certain frame and then growing back to normal in a few frames. I have recorded a video to better demonstrate the problem.

https://www.youtube.com/watch?v=1yzr42fxT90

The beat rate is directly related to the `skipFrames` property in the config (it's 15 in this video). If I change it to 1, the facemesh size will be jumping back and forth every other frame.

**Comment by vladmandic** [comment] 2021-11-20 13:52
the problem is that calculated box size used for caching doesnt have the same crop factor as raw detected box size that comes when re-running detector when cache expires  

ive adjusted and hard coded values for both to minimize impact in human 2.5 (impact was bigger before),  

but problem is still there primarily since blazeface detector will return boxes with different crop factor depending on focal length of detected face - i need to find an exact algorithm to adjust crop factors dynamically and not use fixed values  

for reference:
<https://github.com/vladmandic/human/blob/73333b375b74de6306a906e3628f76fb9de46122/src/face/facemesh.ts#L45>
<https://github.com/vladmandic/human/blob/73333b375b74de6306a906e3628f76fb9de46122/src/face/facemesh.ts#L106>

**Comment by vladmandic** [comment] 2021-11-23 15:40
@ButzYung at the end I've used excel to get a linear fit formula to get r=~2% at different zoom levels

> const calcFactor = config.face.detector.cropFactor / (detectedWidth + 0.75) / 1.34;

new code is in main branch, will be included in upcoming 2.5.4 release by end of this week

**Closed by vladmandic** 2021-11-23 15:40 UTC
Labels: bug
